/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nourw
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Bibliotheque ParisNanterre = new Bibliotheque();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        LabelAdherant = new javax.swing.JLabel();
        LabelLivre = new javax.swing.JLabel();
        LabelOrdi = new javax.swing.JLabel();
        inputNom = new javax.swing.JTextField();
        inputPrenom = new javax.swing.JTextField();
        LabelStatut = new javax.swing.JLabel();
        inputAuteur = new javax.swing.JTextField();
        inputTitre = new javax.swing.JTextField();
        inputEditeur = new javax.swing.JTextField();
        inputMarque = new javax.swing.JTextField();
        LabelEtat = new javax.swing.JLabel();
        LabelSystem = new javax.swing.JLabel();
        ButtonAdherant = new javax.swing.JButton();
        ButtonOrdinateur = new javax.swing.JButton();
        ButtonLivre = new javax.swing.JButton();
        panel3 = new javax.swing.JPanel();
        LabelResultat = new javax.swing.JLabel();
        WindowsBox = new javax.swing.JRadioButton();
        LinuxBox = new javax.swing.JRadioButton();
        NormalBox = new javax.swing.JRadioButton();
        EnPanneBox = new javax.swing.JRadioButton();
        etudiantBox = new javax.swing.JRadioButton();
        enseignantBox = new javax.swing.JRadioButton();
        panel4 = new javax.swing.JPanel();
        AdherantListe = new javax.swing.JButton();
        ListeLivre = new javax.swing.JButton();
        ListeOrdinateurs = new javax.swing.JButton();
        rendreButton = new javax.swing.JButton();
        empruntButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paris - Nanterre ");
        setBackground(new java.awt.Color(0, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panel1.setBackground(new java.awt.Color(255, 0, 51));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion de la Bibliothèque - Paris Nanterre");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelAdherant.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelAdherant.setText("Ajouter un Adhérant ");

        LabelLivre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelLivre.setText("Ajouter un Livre ");

        LabelOrdi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelOrdi.setText("Ajouter un Ordinateur  ");

        inputNom.setText("Nom");

        inputPrenom.setText("Prenom");
        inputPrenom.setToolTipText("");

        LabelStatut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelStatut.setText("Statut");

        inputAuteur.setText("Auteur");

        inputTitre.setText("Titre");

        inputEditeur.setText("Editeur");
        inputEditeur.setToolTipText("");

        inputMarque.setText("Marque");

        LabelEtat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelEtat.setText("Etat");

        LabelSystem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelSystem.setText("Système");

        ButtonAdherant.setText("Ajoter");
        ButtonAdherant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdherantActionPerformed(evt);
            }
        });

        ButtonOrdinateur.setText("Ajouter");
        ButtonOrdinateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOrdinateurActionPerformed(evt);
            }
        });

        ButtonLivre.setText("Ajouter");
        ButtonLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLivreActionPerformed(evt);
            }
        });

        panel3.setBackground(new java.awt.Color(255, 0, 51));
        panel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelResultat.setBackground(new java.awt.Color(255, 255, 255));
        LabelResultat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LabelResultat.setForeground(new java.awt.Color(255, 255, 255));
        LabelResultat.setText("Résultat : ");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LabelResultat)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        buttonGroup2.add(WindowsBox);
        WindowsBox.setText("Windows");

        buttonGroup2.add(LinuxBox);
        LinuxBox.setText("Linux");

        buttonGroup3.add(NormalBox);
        NormalBox.setText("Normal");

        buttonGroup3.add(EnPanneBox);
        EnPanneBox.setText("En Panne");

        buttonGroup1.add(etudiantBox);
        etudiantBox.setText("Etudiant");

        buttonGroup1.add(enseignantBox);
        enseignantBox.setText("Enseignant");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAdherant)
                                    .addComponent(inputNom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonAdherant))
                                .addGap(75, 75, 75)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelLivre)
                                    .addComponent(inputAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputEditeur, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonLivre)))
                            .addComponent(inputPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etudiantBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enseignantBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonOrdinateur)
                            .addComponent(LabelOrdi)
                            .addComponent(inputMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WindowsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LinuxBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NormalBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnPanneBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelAdherant)
                            .addComponent(LabelLivre)
                            .addComponent(LabelOrdi))
                        .addGap(24, 24, 24)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSystem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelStatut)
                            .addComponent(inputEditeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WindowsBox))
                        .addGap(5, 5, 5)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LinuxBox)
                            .addComponent(etudiantBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelEtat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enseignantBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NormalBox)
                .addGap(10, 10, 10)
                .addComponent(EnPanneBox)
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAdherant)
                    .addComponent(ButtonOrdinateur)
                    .addComponent(ButtonLivre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AdherantListe.setText("Les Adhérant");
        AdherantListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdherantListeActionPerformed(evt);
            }
        });

        ListeLivre.setText("Les Livres");

        ListeOrdinateurs.setText("Les Ordinateurs");

        rendreButton.setText("rendre");

        empruntButton.setText("Effectuer un Emprunt");
        empruntButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empruntButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rendreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdherantListe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListeLivre, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(ListeOrdinateurs, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(empruntButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AdherantListe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListeLivre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListeOrdinateurs)
                .addGap(196, 196, 196)
                .addComponent(empruntButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rendreButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void AdherantListeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
      
    }                                             

    private void empruntButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void ButtonAdherantActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        boolean estEtudiant = etudiantBox.isSelected();

    // VÃ©rifier si la case Ã  cocher "Enseignant" est cochÃ©e
        boolean estEnseignant = enseignantBox.isSelected();

    // Utiliser les valeurs boolean pour dÃ©terminer le statut
    Statut statut;
    if (estEtudiant) {
        statut = Statut.ETUDIANT;
    } else if (estEnseignant) {
        statut = Statut.ENSEIGNANT;
    } else {
        // Cas oÃ¹ aucune case n'est cochÃ©e (statut non dÃ©fini)
        statut = null;
    }
    
    String nom = inputNom.getText();
    String prenom = inputPrenom.getText();

    // CrÃ©er un nouvel adhÃ©rent
    Adherant Adherante = new Adherant(nom, prenom, statut);
    
    // Ajouter l'adhÃ©rent Ã  la bibliothÃ¨que
   
    ParisNanterre.ajouterAdherant(Adherante);
    
    // Afficher un message pour indiquer que l'adhÃ©rent a Ã©tÃ© ajoutÃ©
    LabelResultat.setText( Adherante.getprenom() + " " + Adherante.getnom() + " a été bien ajouté Ãà la bibliothèque.");
  
  
    
        
    }                                              

    private void ButtonLivreActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    String titre = inputTitre.getText();
    String auteur = inputAuteur.getText();
    String editeur = inputEditeur.getText();

    // CrÃ©er un nouvel Livre
    Livre MonLivre = new Livre(titre, auteur, editeur , true);
    
    // Ajouter le Livre Ã  la bibliothÃ¨que
   
    ParisNanterre.ajouterDocument(MonLivre);
    
    // Afficher un message pour indiquer que le Livre a Ã©tÃ© ajoutÃ©
    LabelResultat.setText( " Le Livre " + MonLivre.getTitre() + " écrit par  " + MonLivre.getAuteur() + " a été bien ajouté à  la bibliothèque.");
  
        
        
    }                                           

    private void ButtonOrdinateurActionPerformed(java.awt.event.ActionEvent evt) {                                                 
                                                      
        // TODO add your handling code here:
        boolean estWindows = WindowsBox.isSelected();

    // VÃ©rifier si la case Ã  cocher "Linux" est cochÃ©e
        boolean estLinux = LinuxBox.isSelected();

    // Utiliser les valeurs boolean pour dÃ©terminer le System Os
    Os system;
    if (estWindows) {
        system = Os.WINDOWS;
    } else if (estLinux) {
        system = Os.LINUX;
    } else {
        // Cas oÃ¹ aucune case n'est cochÃ©e (Os non dÃ©fini)
        system = null;
    }
    ///////////////////////////////////////// En Panne/Normal :
       

    // VÃ©rifier si la case Ã  cocher "en panne" est cochÃ©e
       

    // Utiliser les valeurs boolean pour dÃ©terminer l'Ã©tat de l'ordinateur
    boolean etat = false;
    if (NormalBox.isSelected()) {
        etat =true;

    } else if (EnPanneBox.isSelected()) {
         etat = false;
    }
  
   
    
    String marque = inputMarque.getText();
   

    // CrÃ©er un nouveau ordinateur
    OrdinateurPortable ordinateur = new OrdinateurPortable(true ,marque,system,etat);
    
    // Ajouter l'adhÃ©rent Ã  la bibliothÃ¨que
   
    ParisNanterre.ajouterMateriel(ordinateur);
    
    // Afficher un message pour indiquer que l'adhÃ©rent a Ã©tÃ© ajoutÃ©
    LabelResultat.setText( "L'ordinateur " + ordinateur.getMarque() + " du Os " + ordinateur.getSystem() + " a été bien ajoué à  la bibliothèque.");
        
                 
        
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AdherantListe;
    private javax.swing.JButton ButtonAdherant;
    private javax.swing.JButton ButtonLivre;
    private javax.swing.JButton ButtonOrdinateur;
    private javax.swing.JRadioButton EnPanneBox;
    private javax.swing.JLabel LabelAdherant;
    private javax.swing.JLabel LabelEtat;
    private javax.swing.JLabel LabelLivre;
    private javax.swing.JLabel LabelOrdi;
    private javax.swing.JLabel LabelResultat;
    private javax.swing.JLabel LabelStatut;
    private javax.swing.JLabel LabelSystem;
    private javax.swing.JRadioButton LinuxBox;
    private javax.swing.JButton ListeLivre;
    private javax.swing.JButton ListeOrdinateurs;
    private javax.swing.JRadioButton NormalBox;
    private javax.swing.JRadioButton WindowsBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton empruntButton;
    private javax.swing.JRadioButton enseignantBox;
    private javax.swing.JRadioButton etudiantBox;
    private javax.swing.JTextField inputAuteur;
    private javax.swing.JTextField inputEditeur;
    private javax.swing.JTextField inputMarque;
    private javax.swing.JTextField inputNom;
    private javax.swing.JTextField inputPrenom;
    private javax.swing.JTextField inputTitre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JButton rendreButton;
    // End of variables declaration                   
}
